export {default as ContactUs} from "./ContactUs"
export {default as Gallery} from "./Gallery"
export {default as HomePage} from "./HomePage"
export {default as Index} from "./Index"
export {default as Menu} from "./Menu" 
export {default as wingselections} from "./wingselections"